gallery/gallery.bak/urls.py
from django.conf.urls.defaults import *
from gallery.settings import ROOT_URL

urlpatterns = patterns('',
    url(r'^%s' % ROOT_URL[1:], include('gallery.real_urls')),
)

gallery/gallery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('items.urls')),
)

gallery/items.bak/urls.py
from django.conf.urls.defaults import *
from gallery.items.models import Item, Photo

urlpatterns = patterns('django.views.generic',
    url(r'^$', 'simple.direct_to_template', 
        kwargs={
            'template': 'index.html',
            'extra_context': {'item_list': lambda: Item.objects.all()}
        },
        name='index'
    ),
    url(r'^items/$', 'list_detail.object_list',
        kwargs={
            'queryset': Item.objects.all(),
            'template_name': 'items_list.html',
            'allow_empty': True
        },
        name='item_list'
    ),
    url(r'^items/(?P<object_id>\d+)/$', 'list_detail.object_detail',
        kwargs={
            'queryset': Item.objects.all(),
            'template_name': 'items_detail.html'
        },
        name='item_detail'
    ),
    url(r'^photos/(?P<object_id>\d+)/$', 'list_detail.object_detail', 
        kwargs={
            'queryset': Photo.objects.all(),
            'template_name': 'photos_detail.html'
        },
        name='photo_detail'
    ),
)

gallery/items/urls.py
from django.conf.urls.defaults import *
from items.views import *

urlpatterns = patterns('',
    # url(r'^$',IndexView.as_view(),name='home'),
    url(r'^$',IndexView,name='home'),
    url(r'^items/$',ItemsView,name='list'),
    url(r'^items/(?P<object_id>\d+)/$',DetailView,name='detail'),
    url(r'^photos/(?P<object_id>\d+)/$',PhotoView,name='photo'),
)

gallery/items.bak/models.py
from django.db import models
from django.db.models import permalink
from django.contrib import admin

from items.fields import ThumbnailImageField

class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    class Meta:
        ordering = ['name']
        
    def __unicode__(self):
        return self.name
        
    @permalink
    def get_absolute_url(self):
        return ('item_detail', None, {'object_id': self.id})

class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)
        
    class Meta:
        ordering = ['title']
        
    def __unicode__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return ('photo_detail', None, {'object_id': self.id})

class PhotoInline(admin.StackedInline):
    model = Photo

class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline]

admin.site.register(Item, ItemAdmin)    
admin.site.register(Photo)

gallery/items/models.py
from django.db import models
from django.contrib import admin
from django.core.urlresolvers import reverse

from items.fields import ThumbnailImageField

class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    class Meta:
        ordering = ['name']
        
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('items.views.DetailView',args=[str(self.id)])
        # reverse('path_to_views',argument),return path to some site

class Photo(models.Model):
    item = models.ForeignKey(Item)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)
        
    class Meta:
        ordering = ['title']
        
    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('items.views.PhotoView',args=[str(self.id)])

class PhotoInline(admin.StackedInline):
    model = Photo

class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline]

admin.site.register(Item, ItemAdmin)    
admin.site.register(Photo)

gallery/items.bak/views.py
# Create your views here.

gallery/items/views.py
from django.views.generic import TemplateView
from items.models import Item,Photo
from django.template import loader,Context
from django.http import HttpResponse

# class IndexView(TemplateView):

# 	template_name="index.html"
	
# 	def get_context_data(self,**kwargs):
# 		context=super(IndexView,self).get_context_data(**kwargs)
# 		context['item_list']=lambda: Item.objects.all()
# 		return context

def IndexView(request):
	item=Item.objects.all()
	t=loader.get_template("index.html")
	c=Context({'item_list':item})
	return HttpResponse(t.render(c))

# class ItemsView(TemplateView):

# 	template_name="items_list.html"

# 	def get_context_data(self,**kwargs):
# 		context=super(ItemsView,self).get_context_data(**kwargs)
# 		context['object_list']=Item.objects.all()
# 		context['allow_empty']=True
# 		return context

def ItemsView(request):
	item=Item.objects.all()
	t=loader.get_template("items_list.html")
	c=Context({'object_list':item})
	return HttpResponse(t.render(c))

def DetailView(request,object_id):
	item=Item.objects.get(id=object_id)
	t=loader.get_template("items_detail.html")
	c=Context({'object':item})
	return HttpResponse(t.render(c))

def PhotoView(reques,object_id):
	photo=Photo.objects.get(id=object_id)
	t=loader.get_template("photos_detail.html")
	c=Context({'object':photo})
	return HttpResponse(t.render(c))

gallery/items.bak/templates/base.html
<html>
    <head>
        <title>Gallery - {% block title %}{% endblock %}</title>
        <style type="text/css">
            body { margin: 30px; font-family: sans-serif; background: #fff; }
            h1 { background: #ccf; padding: 20px; }
            h2 { background: #ddf; padding: 10px 20px; }
            h3 { background: #eef; padding: 5px 20px; }
            table { width: 100%; }
            table th { text-align: left; }
        </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

gallery/items.bak/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<h2>Welcome to the Gallery!</h3>
<p>Here you'll find pictures of various items. Below are some highlighted
items; use the link at the bottom to see the full listing.</p>

<h3>Showcase</h3>
<table>
    <tr>
    {% for item in item_list|slice:":3" %}
        <td>
            <a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br />
            {% if item.photo_set.count %}
                <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
            {% else %}
                <span>No photos (yet)</span>
            {% endif %}
            </a>
        </td>
    {% endfor %}
    </tr>
</table>
<p><a href="{% url item_list %}">View the full list &raquo;</a></p>

{% endblock %}

gallery/items.bak/templates/items_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}

<p><a href="{% url item_list %}">&laquo; Back to full listing</a></p>

<h2>{{ object.name }}</h2>
<p>{{ object.description }}</p>

<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in object.photo_set.all %}
    <tr>
        <td><i>{{ photo.title }}</i></td>
        <td>
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" />
            </a>
        </td>
        <td>{{ photo.caption }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

gallery/items.bak/templates/items_list.html
{% extends "base.html" %}

{% block title %}Item List{% endblock %}

{% block content %}

<p><a href="{% url index %}">&laquo; Back to main page</a></p>

<h2>Items</h2>
{% if object_list %}
<table>
    <tr>
        <th>Name</th>
        <th>Sample Thumb</th>
        <th>Description</th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td><i>{{ item.name }}</i></td>
        <td>
            {% if item.photo_set.count %}
            <a href="{{ item.get_absolute_url }}">
                <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
            </a>
            {% else %}
            (No photos currently uploaded)
            {% endif %}
        </td>
        <td>{{ item.description }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are currently no items to display.</p>
{% endif %}

{% endblock %}

gallery/items.bak/templates/photos_detail.html
{% extends "base.html" %}

{% block title %}{{ object.item.name }} - {{ object.title }}{% endblock %}

{% block content %}

<a href="{{ object.item.get_absolute_url }}">&laquo; Back to {{ object.item.name }} detail page</a>

<h2>{{ object.item.name }} - {{ object.title }}</h2>
<img src="{{ object.image.url }}" />
{% if object.caption %}<p>{{ object.caption }}</p>{% endif %}

{% endblock %}

gallery/items/templates/base.html
<html>
    <head>
        <title>Gallery - {% block title %}{% endblock %}</title>
        <style type="text/css">
            body { margin: 30px; font-family: sans-serif; background: #fff; }
            h1 { background: #ccf; padding: 20px; }
            h2 { background: #ddf; padding: 10px 20px; }
            h3 { background: #eef; padding: 5px 20px; }
            table { width: 100%; }
            table th { text-align: left; }
        </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

gallery/items/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<h2>Welcome to the Gallery!</h3>
<p>Here you'll find pictures of various items. Below are some highlighted
items; use the link at the bottom to see the full listing.</p>

<h3>Showcase</h3>
<table>
    <tr>
    {% for item in item_list|slice:":3" %}
        <td>
            <a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br />
            {% if item.photo_set.count %}
                <a href="{{ item.photo_set.get_absolute_url }}"><img src="{{ item.photo_set.all.0.image.thumb_url }}" /></a>
            {% else %}
                <span>No photos (yet)</span>
            {% endif %}
            </a>
        </td>
    {% endfor %}
    </tr>
</table>
<p><a href="{% url 'items.views.ItemsView' %}">View the full list &raquo;</a></p>
<!-- url 'path_to_views' argument  -->

{% endblock %}

gallery/items/templates/items_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}

<p><a href="{% url 'items.views.IndexView' %}">&laquo; Back to full listing</a></p>

<h2>{{ object.name }}</h2>
<p>{{ object.description }}</p>

<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in object.photo_set.all %}
    <tr>
        <td><i>{{ photo.title }}</i></td>
        <td>
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.image.thumb_url }}" />
            </a>
        </td>
        <td>{{ photo.caption }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

gallery/items/templates/items_list.html
{% extends "base.html" %}

{% block title %}Item List{% endblock %}

{% block content %}

<p><a href="{% url 'items.views.IndexView' %}">&laquo; Back to main page</a></p>

<h2>Items</h2>
{% if object_list %}
<table>
    <tr>
        <th>Name</th>
        <th>Sample Thumb</th>
        <th>Description</th>
    </tr>
    {% for item in object_list %}
    <tr>
        <td><i>{{ item.name }}</i></td>
        <td>
            {% if item.photo_set.count %}
            <a href="{{ item.get_absolute_url }}">
                <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
            </a>
            {% else %}
            (No photos currently uploaded)
            {% endif %}
        </td>
        <td>{{ item.description }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are currently no items to display.</p>
{% endif %}

{% endblock %}

gallery/items/templates/photos_detail.html
{% extends "base.html" %}

{% block title %}{{ object.item.name }} - {{ object.title }}{% endblock %}

{% block content %}

<a href="{{ object.item.get_absolute_url }}">&laquo; Back to {{ object.item.name }} detail page</a>

<h2>{{ object.item.name }} - {{ object.title }}</h2>
<img src="{{ object.image.url }}" />
{% if object.caption %}<p>{{ object.caption }}</p>{% endif %}

{% endblock %}